### PR TITLE
Add run on replit

### PR DESCRIPTION
**Pull request by hackermondev**
Replit is a thing like Heroku but it's better @MrPowerScripts 

https://replit.com

### CODE REVIEW

**Comment by MrPowerScripts** [comment]
We had this before but had to remove it for some reason. This probably needs its own doc on how to set it up. like how do the credentials get added?

**Comment by igosad** [comment]
I deleted the Replit template because Replit used to have a "feature" (that's what they said) which show the console log to the public like this <repl>.<user>.repl.co/__logs
so that's going to show the credentials because the bot print the credentials on start.
That's why MRPS removed it .

**Comment by MrPowerScripts** [comment]
Oh I forgot about that. thanks for the reminder! I think we can leave hosted services out of the docs at this point. it didn't go so well with heroku anyway and got a lot of peoples hosting accounts banned.

**Comment by hackermondev** [comment]
> I deleted the Replit template because Replit used to have a "feature" (that's what they said) which show the console log to the public like this ..repl.co/__logs
> so that's going to show the credentials because the bot print the credentials on start.
> That's why MRPS removed it .

they removed that, the page still exists but it doesn't show the logs anymore

**Pull request closed without merging**
