### PR TITLE
Command line gsheets karma farmer

### PR DESCRIPTION
**Pull request by HarryBak**

### CODE REVIEW

**Comment by HarryBak** [comment]
idk what im doing i don't want to push this? hahah

**Comment by MrPowerScripts** [comment]
My dude is that an actual private key that you submitted in the PR?

**Comment by zegevlier** [comment]
The drive link is also accessible to anyone.

**Comment by recoiil** [comment]
lmao nice also mrpowerscripts i love you and i think its cool your still updating this project i made this github account just to say that

**Comment by MrPowerScripts** [comment]
I like this but there's tool many breaking changes at the moment and I don't have time to fix them, so I'm going to close this PR for now and we ca revisit it in the future

**Pull request closed without merging**
