### PR TITLE
Update config_gen.py

### PR DESCRIPTION
**Pull request by igosad**
fix to #189 #188 #186

### CODE REVIEW

**Comment by digitalftl** [comment]
I've tried this update on Ubuntu 20.4 it works.

**Comment by MrPowerScripts** [comment]
I think it would be good to know why the config parser package causes this issue. What is the difference between the config file generated using configparser, or by generating the lines manually?

**Comment by igosad** [comment]
> I think it would be good to know why the config parser package causes this issue. What is the difference between the config file generated using configparser, or by generating the lines manually?

i think that the `[REDDIT_AUTH]` is causing the the problem cuz when i removed it manually the bot imported the environment variable with out a problem and i couldn't make the configparser generate the .env file with out the header  `[REDDIT_AUTH]`

**Comment by MrPowerScripts** [comment]
I don't remember why I used configparser. But it doesn't seem like it's used anywhere else in the app. so it's probably safe to remove for now if it gets this working.

**Pull request merged**
