### PR TITLE
Update disallowed_subs.txt

### PR DESCRIPTION
**Pull request by psywarrior1998**

### CODE REVIEW

**Comment by kiityman1** [comment]
This gets rid of a lot of the good subs for karma.

Some shouldn't even ban you (such as r/videos or r/aww - which are both amazing for karma)

**Comment by psywarrior1998** [comment]
Both of them did ban one of my bots which didnt even did more than one posts or an non related posts on those

**Comment by taiten312** [comment]
Not to mention, that you didn't had to include NSFW subs, afaik the bot doesn't post in subs flagged as NSFW.

**Comment by psywarrior1998** [comment]
> I don't think you meant to submit this? This would change the Heroku to launch from your account.
> EDIT: And you changed the min DB size, this would make it so that users would have to way about 4x as long, which we absolutely do not want. I also agree with kiityman1 that you added some subreddits that don't ban fast that give really good karma. I don't think this should be merged


yeah there were some extra things that I committed after making the pull request but they were added nonetheless 
also the thing is they do ban in about a period of 8 hours or less as what I have personally experienced so that the reason I have added them

**Comment by MrPowerScripts** [comment]
I kinda feel like it might actually be better to ban a lot of the bigger subs by default, and let people remove them if they want. this might prevent a lot of needless bans if we know those subs will detect the bot quickly and ban it. and it gives me time to work on a system that allows for more granular control of when subs can be used. but you need to remove all the other file edits and remove the nswf subs, because we block all of those automatically.

**Comment by psywarrior1998** [comment]
I will do it tomorrow when i wake up

**Comment by psywarrior1998** [comment]
I will do it tomorrow when i wake up

**Pull request closed without merging**
