### PR TITLE
New UI

### PR DESCRIPTION
**Pull request by Xpl0itU**
It's not done at a 100% but you can finish it if you want, the functionality is there, so it can be merged in the current state

### CODE REVIEW

**Review by EliteDaMyth — APPROVED** [review]
looks very cool!

**Comment by Xpl0itU** [comment]
Thanks! Is there anything you would change or add? Feedback helps a lot

**Review by AidenWTF — APPROVED** [review]
Very nicely made

**Comment by MrPowerScripts** [comment]
I  will check this out as soon as I can!

**Pull request merged**
